---
- name: "Configure namenode"
  hosts: namenode
  vars_files:
  - var.txt
  tasks:
  - name: "Copying software"
    copy:
     src: "/root/hadoop_software"
     dest: "/root"

  - name: "installing hadoop software"
    shell: "rpm -ivh /root/hadoop_software/hadoop-1.2.1-1.x86_64.rpm --force"
    ignore_errors: yes

  - name: "installing jdk software"
    shell: "rpm -ivh /root/hadoop_software/jdk-8u281-linux-x64.rpm"
    ignore_errors: yes

  - name: "creating folder /nn" 
    file:
      name: "{{ dir_name }}"
      state: directory
  
  - name: "Configuring hdfs-file"
    template:
      src: "/root/task11file/name-hdfs.xml"
      dest: "/etc/hadoop/hdfs-site.xml"

  - name: "Configuring core-file"      
    template:                          
      src: "/root/task11file/name-core.xml"
      dest: "/etc/hadoop/core-site.xml"                                        
  
  - name: "format namenode"
    shell: "echo Y | hadoop namenode -format"
    ignore_errors: yes
    
  - name: "start hadoop service"
    shell: "hadoop-daemon.sh start namenode"
    ignore_errors: yes

###############################################################
- name: "Configure datanode"
  hosts: datanode
  vars_files:
  - var.txt
  tasks:
  - name: "Copying software"
    copy:
     src: "/root/hadoop_software"
     dest: "/root"
   
  - name: "installing hadoop software"
    shell: "rpm -ivh /root/hadoop_software/hadoop-1.2.1-1.x86_64.rpm --force"
    ignore_errors: yes
   
  - name: "installing jdk software"
    shell: "rpm -ivh /root/hadoop_software/jdk-8u281-linux-x64.rpm"
    ignore_errors: yes
   
  - name: "creating folder /nn"
    file:                  
     name: "{{ dir_data }}"
     state: directory     
                             
  - name: "Configuring hdfs-file"
    template:              
      src: "/root/task11file/data-hdfs.xml"
      dest: "/etc/hadoop/hdfs-site.xml"
                             
  - name: "Configuring core-file"
    template:               
     src: "/root/task11file/data-core.xml"
     dest: "/etc/hadoop/core-site.xml"
                             
  - name: "matching id"
    file:
     name: "{{ dir_data }}"
     state: absent
  
  - name: "matching id"
    file:
     name: "{{ dir_data }}"
     state: directory

  - name: "start datanode service"
    shell: "hadoop-daemon.sh start datanode"

